# -*- coding: utf-8 -*-
"""STUDENT_MANAGEMENT_SYSTEM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iOrMH6ZxCEXgTB_G8s94ng5lNZ_Cdg9b
"""

from abc import ABC, abstractmethod


# ============================================================
# 1. ABSTRACT BASE CLASS
# ============================================================
class Person(ABC):

    def __init__(self, name):
        self.__name = ""
        self.set_name(name)

    def get_name(self):
        return self.__name

    def set_name(self, name):
        name = name.strip()
        if not name or "|" in name:
            raise ValueError("Name cannot be empty or contain '|'.")
        self.__name = name

    @abstractmethod
    def display_info(self):
        pass


# ============================================================
# 2. STUDENT CLASS
# ============================================================
class Student(Person):

    def __init__(self, roll_no, name, marks):
        super().__init__(name)
        self.__roll_no = ""
        self.__marks = 0.0

        self.set_roll_no(roll_no)
        self.set_marks(marks)

    def get_roll_no(self):
        return self.__roll_no

    def set_roll_no(self, roll_no):
        roll_no = roll_no.strip()
        if not roll_no or "|" in roll_no:
            raise ValueError("Roll number cannot be empty or contain '|'.")
        self.__roll_no = roll_no

    def get_marks(self):
        return self.__marks

    def set_marks(self, marks):
        try:
            marks = float(marks)
        except (ValueError, TypeError):
            raise ValueError("Marks must be a valid number.")

        if 0 <= marks <= 100:
            self.__marks = marks
        else:
            raise ValueError("Marks must be between 0 and 100.")

    def display_info(self):
        print(f"Roll Number : {self.__roll_no}")
        print(f"Name        : {self.get_name()}")
        print(f"Marks       : {self.__marks:.2f}")
        print("-" * 30)

    def to_file_format(self):
        return f"{self.__roll_no}|{self.get_name()}|{self.__marks}"


# ============================================================
# 3. FILE MANAGER CLASS
# ============================================================
class FileManager:

    FILE_NAME = "students.txt"

    def save_students(self, students):
        try:
            with open(self.FILE_NAME, "w", encoding="utf-8") as file:
                for student in students:
                    file.write(student.to_file_format() + "\n")
            print("Records saved successfully!")
        except IOError:
            print("Error: Unable to save records to file.")

    def load_students(self):
        students = []
        try:
            with open(self.FILE_NAME, "r", encoding="utf-8") as file:
                for line in file:
                    line_str = line.strip()
                    if not line_str:
                        continue
                    try:
                        data = line_str.split("|")
                        if len(data) != 3:
                            raise ValueError("Invalid field count.")

                        roll_no, name, marks = data[0], data[1], float(data[2])
                        students.append(Student(roll_no, name, marks))
                    except ValueError:
                        print(f"Skipped invalid record: {line_str}")
        except FileNotFoundError:
            pass  # File will be created on first save
        except IOError:
            print("Error while reading student records.")

        return students


# ============================================================
# 4. STUDENT MANAGER CLASS
# ============================================================
class StudentManager:

    def __init__(self):
        self.file_manager = FileManager()
        self.students = self.file_manager.load_students()

    def add_student(self):
        try:
            roll_no = input("Enter Roll Number: ").strip()

            if any(s.get_roll_no() == roll_no for s in self.students):
                print("Error: A student with this roll number already exists.")
                return

            name = input("Enter Student Name: ").strip()
            marks_input = input("Enter Marks (0-100): ").strip()

            # Constructor handles full validation
            student = Student(roll_no, name, marks_input)
            self.students.append(student)
            print("Student added successfully!")

        except ValueError as error:
            print("Invalid input:", error)

    def display_students(self):
        if not self.students:
            print("No student records found.")
            return

        print("\n========== STUDENT RECORDS ==========")
        for student in self.students:
            student.display_info()

    def search_student(self):
        roll_no = input("Enter Roll Number to search: ").strip()
        for student in self.students:
            if student.get_roll_no() == roll_no:
                print("\nStudent Found!")
                student.display_info()
                return
        print("Student not found.")

    def update_student(self):
        roll_no = input("Enter Roll Number to update: ").strip()
        for student in self.students:
            if student.get_roll_no() == roll_no:
                try:
                    new_name = input("Enter New Name: ").strip()
                    new_marks = input("Enter New Marks: ").strip()

                    # Temporary validation check
                    temp_student = Student(roll_no, new_name, new_marks)

                    student.set_name(temp_student.get_name())
                    student.set_marks(temp_student.get_marks())

                    print("Student record updated successfully!")
                    return
                except ValueError as error:
                    print("Invalid input:", error)
                    return
        print("Student not found.")

    def delete_student(self):
        roll_no = input("Enter Roll Number to delete: ").strip()
        for student in self.students:
            if student.get_roll_no() == roll_no:
                self.students.remove(student)
                print("Student deleted successfully!")
                return
        print("Student not found.")

    def calculate_average(self):
        if not self.students:
            print("No student records found.")
            return

        total = sum(s.get_marks() for s in self.students)
        average = total / len(self.students)

        print("\nTotal Students :", len(self.students))
        print("Average Marks  :", round(average, 2))

    def save_records(self):
        self.file_manager.save_students(self.students)


# ============================================================
# MAIN PROGRAM
# ============================================================
def main():
    manager = StudentManager()

    while True:
        print("\n======================================")
        print("      --- STUDENT MANAGEMENT SYSTEM  ---")
        print("======================================")
        print("1. Add Student")
        print("2. Display Students")
        print("3. Search Student")
        print("4. Update Student")
        print("5. Delete Student")
        print("6. Calculate Average Marks")
        print("7. Save Records")
        print("8. Exit")
        print("======================================")

        choice = input("Enter your choice: ").strip()

        if choice == "1":
            manager.add_student()
        elif choice == "2":
            manager.display_students()
        elif choice == "3":
            manager.search_student()
        elif choice == "4":
            manager.update_student()
        elif choice == "5":
            manager.delete_student()
        elif choice == "6":
            manager.calculate_average()
        elif choice == "7":
            manager.save_records()
        elif choice == "8":
            manager.save_records()
            print("Thank you for using Student Management System!")
            break
        else:
            print("Invalid choice! Please enter 1-8.")


if __name__ == "__main__":
    main()